apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-nwcf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-rbve-tenant/appstudio/dc-metro-map-nwcf@sha256:06916b36287ddbedfabe03a98abe6802f61da740aee8f21028aed11c4fa0aa4c
        name: my-nodejs
        resources: {}
status: {}
