apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-nwcf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-nwcf
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-nwcf
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-nwcf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-nwcf
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-rbve-tenant/appstudio/dc-metro-map-nwcf@sha256:06916b36287ddbedfabe03a98abe6802f61da740aee8f21028aed11c4fa0aa4c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
